name = "SatelliteToolboxTle"
uuid = "7ff27aeb-5fff-4337-a9ee-a9fe6b7ed35e"
license = "MIT"
desc = "Tools to parse and create TLEs (two-line elements)."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.0.1"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Crayons = "4.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[targets]
test = ["Test", "Logging"]
