name = "SatelliteToolboxTle"
uuid = "7ff27aeb-5fff-4337-a9ee-a9fe6b7ed35e"
license = "MIT"
desc = "Tools to parse and create TLEs (two-line elements)."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "1.0.6"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"

[compat]
Crayons = "4.0"
Dates = "1.10"
Downloads = "1.10"
Logging = "1.10"
PrecompileTools = "1"
Printf = "1.10"
Test = "1.10"
URIs = "1.4"
julia = "1.10"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Logging"]
